[package]
name = "rust_gamephysics"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.7.2"
winit = "0.25.0"
ash = "0.33.3"
ash-window = "0.7.0"
termcolor = "1.1.2"